<?php

namespace ContainerVvKEgm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AIPCNEgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AIPCNEg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AIPCNEg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AromatesController::index' => ['privates', '.service_locator.v7NE3Lb', 'get_ServiceLocator_V7NE3LbService', true],
            'App\\Controller\\FruitsController::index' => ['privates', '.service_locator.RxyTpam', 'get_ServiceLocator_RxyTpamService', true],
            'App\\Controller\\VegetablesController::index' => ['privates', '.service_locator.HQ3Ykcz', 'get_ServiceLocator_HQ3YkczService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AromatesController:index' => ['privates', '.service_locator.v7NE3Lb', 'get_ServiceLocator_V7NE3LbService', true],
            'App\\Controller\\FruitsController:index' => ['privates', '.service_locator.RxyTpam', 'get_ServiceLocator_RxyTpamService', true],
            'App\\Controller\\VegetablesController:index' => ['privates', '.service_locator.HQ3Ykcz', 'get_ServiceLocator_HQ3YkczService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AromatesController::index' => '?',
            'App\\Controller\\FruitsController::index' => '?',
            'App\\Controller\\VegetablesController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AromatesController:index' => '?',
            'App\\Controller\\FruitsController:index' => '?',
            'App\\Controller\\VegetablesController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
