<?php

namespace ContainerVvKEgm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V7NE3LbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v7NE3Lb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v7NE3Lb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aromatesRepository' => ['privates', 'App\\Repository\\AromatesRepository', 'getAromatesRepositoryService', true],
        ], [
            'aromatesRepository' => 'App\\Repository\\AromatesRepository',
        ]);
    }
}
