<?php

namespace ContainerVvKEgm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HQ3YkczService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HQ3Ykcz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HQ3Ykcz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vegetablesRepository' => ['privates', 'App\\Repository\\VegetablesRepository', 'getVegetablesRepositoryService', true],
        ], [
            'vegetablesRepository' => 'App\\Repository\\VegetablesRepository',
        ]);
    }
}
