<?php

namespace ContainerVvKEgm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFruitsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FruitsController' shared autowired service.
     *
     * @return \App\Controller\FruitsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\FruitsController.php';

        $container->services['App\\Controller\\FruitsController'] = $instance = new \App\Controller\FruitsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\FruitsController', $container));

        return $instance;
    }
}
