<?php

namespace ContainerVvKEgm5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVegetablesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VegetablesController' shared autowired service.
     *
     * @return \App\Controller\VegetablesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\VegetablesController.php';

        $container->services['App\\Controller\\VegetablesController'] = $instance = new \App\Controller\VegetablesController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\VegetablesController', $container));

        return $instance;
    }
}
