<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvKEgm5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvKEgm5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvKEgm5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvKEgm5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVvKEgm5\App_KernelDevDebugContainer([
    'container.build_hash' => 'VvKEgm5',
    'container.build_id' => '4d62f136',
    'container.build_time' => 1596810238,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvKEgm5');
