<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'aromates' => [[], ['_controller' => 'App\\Controller\\AromatesController::index'], [], [['text', '/aromates']], [], []],
    'fruits_list' => [[], ['_controller' => 'App\\Controller\\FruitsController::index'], [], [['text', '/api/fruits']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'vegetables' => [[], ['_controller' => 'App\\Controller\\VegetablesController::index'], [], [['text', '/vegetables']], [], []],
];
